version: "3.9"
services:
  weather-api-server:
    working_dir: /app
    image: "node:17"
    command: sh -c "npm install && npm install -g nodemon && nodemon bin/www"

    ports:
      - "3000:3000"

    environment:
      DEBUG: weather-api-server:*
      DB_HOST: db

    env_file:
      - "env/dev.env"

    volumes:
      - ./weather-api-server/:/app/

    secrets:
      - postgres-passwd

  query-script:
    working_dir: /app
    command: bash -c "npm install && sleep infinity"
    image: "node:17"
    env_file:
      - "env/dev.env"
    environment:
      DB_HOST: db

    volumes:
      - ./query-script/:/app

    secrets:
      - postgres-passwd
      - weather-apikey

  db:
    image: "postgres"
    env_file:
      - "env/dev.env"

    ports:
      - "5432:5432"

    volumes:
      - ./db/:/docker-entrypoint-initdb.d/

    secrets:
      - postgres-passwd

secrets:
  postgres-passwd:
    file: ./secrets/postgres-passwd

  weather-apikey:
    file: ./secrets/weather-apikey
