version: "3.9"
services:
  weather-api-server:
    image: "ynonp/deploy-weather-to-k8s-weather-api-server:1.0"

    ports:
      - "3000:3000"

    environment:
      DB_HOST: db

    env_file:
      - "env/k8s.env"

    secrets:
      - postgres-passwd

  query-script:
    image: "ynonp/deploy-weather-to-k8s-query-script:1.0"
    env_file:
      - "env/k8s.env"
    environment:
      DB_HOST: db

    secrets:
      - postgres-passwd
      - weather-apikey

  db:
    image: "ynonp/deploy-weather-to-k8s-db:1.0"
    env_file:
      - "env/k8s.env"

    ports:
      - "5432:5432"

    secrets:
      - postgres-passwd

secrets:
  postgres-passwd:
    file: ./secrets/postgres-passwd

  weather-apikey:
    file: ./secrets/weather-apikey

