apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-k8s.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: weather-api-server
  name: weather-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weather-api-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-k8s.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: weather-api-server
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env-production-env
            - name: POSTGRES_PASSWORD_FILE
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD_FILE
                  name: env-production-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env-production-env
            - name: WEATHER_API_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  key: WEATHER_API_KEY_FILE
                  name: env-production-env
          image: ynonp/21-weather-api-server:1.0
          name: weather-api-server
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /run/secrets/postgres-passwd
              name: postgres-passwd
      restartPolicy: Always
      volumes:
        - name: postgres-passwd
          secret:
            items:
              - key: postgres-passwd
                path: postgres-passwd
            secretName: postgres-passwd
status: {}
