version: "3.9"

services:
  db:
    image: postgres:14.2
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

    secrets:
      - postgres-passwd

    env_file: ./env/dev.env

    ports:
      - "5432:5432"

secrets:
  postgres-passwd:
    file: ./secrets/postgres_password
