version: "3.9"

services:
  server:
    image: node:17
    working_dir: /app
    command: bash -c "npm install && npm install -g nodemon && nodemon bin/www"
    volumes:
      - ./server:/app

    env_file: ./env/dev.env

    environment:
      DB_HOST: db

    secrets:
      - postgres-passwd

    ports:
      - "3000:3000"


  query-script:
    image: node:17
    working_dir: /app
    command: sleep infinity

    env_file: ./env/dev.env

    environment:
      DB_HOST: db

    volumes:
      - ./query-script:/app

    secrets:
      - postgres-passwd
      - weatherapi-key

  db:
    image: postgres:14.2
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

    secrets:
      - postgres-passwd

    env_file: ./env/dev.env

    ports:
      - "5432:5432"

secrets:
  postgres-passwd:
    file: ./secrets/postgres_password

  weatherapi-key:
    file: ./secrets/weather-apikey
