version: "3.9"
services:
  db:
    image: "postgres:14.1"
    env_file: ./env/dev.env

    secrets:
      - postgres-passwd

    volumes:
      - ./db/:/docker-entrypoint-initdb.d/

    ports:
      - "5432:5432"

secrets:
  postgres-passwd:
    file: ./secrets/postgres-passwd
