version: "3.9"
services:
  weather-api-server:
    working_dir: "/app"
    image: "node:16"
    command: bash -c "npm install && npm run test:watch"
    env_file:
      - "env/test.env"
    environment:
      DEBUG: weather-api-server:*
    volumes:
      - ./secrets/postgres-passwd:/run/secrets/postgres-passwd
      - ./weather-api-server/:/app

  db:
    image: "postgres"
    env_file:
      - "env/test.env"

    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
      - ./secrets/postgres-passwd:/run/secrets/postgres-passwd

volumes:
  postgres:


