version: "3.8"
services:
  web:
    image: "ynonp/deploy-to-k8s-livedemo:1.0"
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis

  redis:
    image: "redis:6.2-alpine"
    ports:
      - "6379:6379"
    volumes:
      - "data:/data"

volumes:
  data:


